# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Klartui < Formula
  desc "A terminal UI for the Klar BFF
"
  homepage "https://github.com/placeholder-tech/klartui"
  version "0.0.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/placeholder-tech/klartui/releases/download/v0.0.7/klartui_Darwin_x86_64.tar.gz"
      sha256 "61188127b71674e1b071db9350be87387d5f0904150fd68a88fab46416252c08"

      def install
        bin.install "klartui" => "klartui"  # This renames the binary when installing
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/placeholder-tech/klartui/releases/download/v0.0.7/klartui_Darwin_arm64.tar.gz"
      sha256 "bf2d4cf729fe7a35cfd331dac039ea76214956d168eda47c8a818c4d2b937fc6"

      def install
        bin.install "klartui" => "klartui"  # This renames the binary when installing
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/placeholder-tech/klartui/releases/download/v0.0.7/klartui_Linux_x86_64.tar.gz"
      sha256 "b17a8d2dbb14bce906c135b9992bb59c6043de85d3fce5afd4af52dfca0163d9"
      def install
        bin.install "klartui" => "klartui"  # This renames the binary when installing
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/placeholder-tech/klartui/releases/download/v0.0.7/klartui_Linux_arm64.tar.gz"
      sha256 "5fd9f59a3e03b56b4d15b18fb0d1160076f7536307b962795292c02173ab9709"
      def install
        bin.install "klartui" => "klartui"  # This renames the binary when installing
      end
    end
  end

  test do
    system "#{bin}/klartui", "--version"
  end
end
