# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/custom_download_strategy"
class Klartui < Formula
  desc "A terminal UI for the Klar BFF
"
  homepage "https://github.com/placeholder-tech/klartui"
  version "0.0.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/placeholder-tech/klartui/releases/download/v0.0.8/klartui_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "4170d80abdb86b12d8c3b247245be74d63548e957167aadc63d639244c22f4bc"

      def install
        bin.install "klartui" => "klartui"  # This renames the binary when installing
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/placeholder-tech/klartui/releases/download/v0.0.8/klartui_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "fdcb3512b96a5b5473c11b638714333f72ee6851fb15e5c19b9151ef8febcab7"

      def install
        bin.install "klartui" => "klartui"  # This renames the binary when installing
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/placeholder-tech/klartui/releases/download/v0.0.8/klartui_Linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "f22903169a5f3c471b37a48cb169f7162ee7c202dc284d07c79565e565eb50e0"
      def install
        bin.install "klartui" => "klartui"  # This renames the binary when installing
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/placeholder-tech/klartui/releases/download/v0.0.8/klartui_Linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "d6655f45384e6ce12027a75d93cc5d59ebeefe244b9506c2cedc8fb204786328"
      def install
        bin.install "klartui" => "klartui"  # This renames the binary when installing
      end
    end
  end

  test do
    system "#{bin}/klartui", "--version"
  end
end
